/**
 * V7 PHASE 1: write the shared MaterialLibrary as real assets, in the bundle.
 *
 * PHASE 0 found the previous attempt non-functional in three ways:
 *   1. the files sat in `assets/resources/game_art/materials/` instead of the
 *      bundle directory `assets/game_art/materials/`
 *   2. every .meta said `imported: false` - Creator never processed them
 *   3. nothing referenced them, so they shipped in no bundle
 *
 * This script fixes (1) and cleans up after it. (2) and (3) need a Creator
 * import pass, which is the only thing that may assign a uuid; a .prefab that
 * references the materials (v7_phase1_bootstrap.mjs) then forces them into the
 * game-art bundle.
 *
 * Deliberately NOT a collapse of the per-kind tints: the world has 56 art kinds
 * sharing five colour atlases, told apart by a per-kind tint. These assets own
 * the *material definition* (effect, technique, blend/depth state, base colour)
 * and the runtime keeps supplying the per-kind tint and atlas on top, so this
 * removes scattered material construction without flattening 56 looks into 8.
 */
import { mkdirSync, writeFileSync, existsSync, rmSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(repo, 'cocos', 'assets', 'game_art', 'materials');
/** Where the previous run put them: outside the bundle, so they never shipped. */
const strayDir = path.join(repo, 'cocos', 'assets', 'resources', 'game_art');

/** Builtin unlit effect uuid, read from the editor's own effect metadata. */
const EFFECT_UNLIT = 'a3cd009f-0ab0-420d-9278-b9fdab939bbc';

/**
 * The category materials, with the base colour each one carries.
 *
 * `textured` decides the USE_TEXTURE macro, because `builtin-unlit` defaults it
 * to false and will not sample an atlas assigned later.
 */
const MATERIALS = [
  { name: 'MAT_GRASS', colour: '#a6e894', textured: true, note: 'ground and grass tiles' },
  { name: 'MAT_ROAD', colour: '#e8edf5', textured: true, note: 'road, crossroad, kerb, street furniture' },
  { name: 'MAT_BUILDING', colour: '#f7b267', textured: true, note: 'residential and commercial architecture' },
  { name: 'MAT_VEGETATION', colour: '#69bf71', textured: true, note: 'trees, hedges, bushes, flowerbeds' },
  { name: 'MAT_VEHICLE', colour: '#ef476f', textured: true, note: 'traffic vehicles and the player chassis' },
  { name: 'MAT_PROP', colour: '#c68b59', textured: true, note: 'street props and recyclable collectibles' },
  { name: 'MAT_METAL', colour: '#90a4ae', textured: false, note: 'untextured metal parts' },
  { name: 'MAT_BLACKHOLE', colour: '#281660', textured: false, note: 'singularity core parts' },
];

function srgbToLinearChannel(value) {
  const c = value / 255;
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

function toLinearColour(hex) {
  const v = hex.replace('#', '');
  return [0, 2, 4].map((offset) => srgbToLinearChannel(parseInt(v.slice(offset, offset + 2), 16)));
}

/**
 * A cc.Material asset. Shape matches what Creator's own glTF importer writes,
 * which is the authoritative sample in this repository.
 *
 * Extension note: the previous attempt wrote `.material` files and Creator
 * never imported them (every .meta stayed `imported: false`). Creator's asset
 * database routes material assets through the `.mtl` extension and the
 * `material` importer, so that is what this writes. The names stay MAT_*.
 */
function materialAsset(name, colour, textured) {
  const [r, g, b] = toLinearColour(colour);
  return {
    __type__: 'cc.Material',
    _name: name,
    _objFlags: 0,
    __editorExtras__: {},
    _native: '',
    _effectAsset: { __uuid__: EFFECT_UNLIT, __expectedType__: 'cc.EffectAsset' },
    _techIdx: 0,
    _defines: [{ USE_TEXTURE: textured, USE_VERTEX_COLOR: false }],
    _states: [{
      rasterizerState: { cullMode: 0 },
      blendState: { targets: [{}] },
      depthStencilState: {},
    }],
    _props: [{
      mainColor: {
        __type__: 'cc.Color',
        r: Math.round(r * 255),
        g: Math.round(g * 255),
        b: Math.round(b * 255),
        a: 255,
      },
      tilingOffset: { __type__: 'cc.Vec4', x: 1, y: 1, z: 0, w: 0 },
    }],
  };
}

const cleanup = (dir) => {
  if (!existsSync(dir)) return 0;
  const victims = readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /^MAT_[A-Z]+\.(material|mtl)(\.meta)?$/.test(entry.name))
    .map((entry) => path.join(dir, entry.name));
  for (const victim of victims) rmSync(victim, { force: true });
  return victims.length;
};

// The previous run's output is untracked scratch generated by this same
// generator; removing it leaves exactly one authoritative copy inside the
// bundle. Only remove files this generator would have written.
const removed = cleanup(path.join(strayDir, 'materials')) + cleanup(outDir);
if (removed) console.log('removed ' + removed + ' stale material file(s) from a previous run');
for (const leftover of ['materials', 'game_art']) {
  const dir = path.join(strayDir, leftover);
  if (existsSync(dir) && readdirSync(dir).length === 0) rmSync(dir, { recursive: true, force: true });
}
if (existsSync(strayDir) && readdirSync(strayDir).length === 0) {
  rmSync(strayDir, { recursive: true, force: true });
}

mkdirSync(outDir, { recursive: true });
for (const material of MATERIALS) {
  const file = path.join(outDir, material.name + '.mtl');
  writeFileSync(file, JSON.stringify(materialAsset(material.name, material.colour, material.textured), null, 2) + '\n', 'utf8');
  console.log('wrote ' + material.name + '.mtl  ' + material.colour + '  (' + material.note + ')');
}
console.log('\n' + MATERIALS.length + ' category materials written to ' + path.relative(repo, outDir));
console.log('Creator must now import them; that is what assigns their uuids.');
