/**
 * Bundle-backed sound-effect library.
 *
 * Mirrors `UIAssetLibrary`: same `game-art` bundle, same retry/deduplication
 * service, same rule that a missing asset is reported rather than silently
 * substituted. The audio clips are generated by `scripts/generate_audio_sfx.mjs`
 * and are **provisional** -- real, audible synthesis standing in until licensed
 * production audio is bought. Nothing here pretends otherwise: `getLastError()`
 * names any clip that failed to load, and `AudioDirector` counts the plays that
 * had no clip behind them.
 */
import { AssetManager, AudioClip } from 'cc';
import { RegionBundleService } from '../world/RegionBundleService';

const BUNDLE = 'game-art';

/**
 * Bundle paths, relative to the bundle root. `AudioClip` has no sub-asset, so the
 * bare path is the only attempt -- unlike a PNG, which registers as an ImageAsset
 * with Texture2D and SpriteFrame sub-assets.
 */
export const AUDIO_CLIP_PATHS = {
  absorb: 'audio/sfx_absorb',
  swallow: 'audio/sfx_swallow',
  upgrade: 'audio/sfx_upgrade',
  kill: 'audio/sfx_kill',
  death: 'audio/sfx_death',
  button: 'audio/sfx_button',
  reward: 'audio/sfx_reward',
} as const;

export type AudioClipKey = keyof typeof AUDIO_CLIP_PATHS;

const CLIP_KEYS = Object.keys(AUDIO_CLIP_PATHS) as AudioClipKey[];

export class AudioAssetLibrary {
  private static readonly bundles = new RegionBundleService({ maxAttempts: 3, retryDelayMs: 200 });
  private static readonly clips = new Map<AudioClipKey, AudioClip>();
  private static waiters: Array<() => void> = [];
  private static pending = false;
  private static requested = false;
  private static lastError: string | null = null;

  /** Begin loading once. Callers arriving mid-flight register with `whenReady`. */
  public static ensure(): void {
    if (AudioAssetLibrary.requested) return;
    AudioAssetLibrary.requested = true;
    AudioAssetLibrary.pending = true;

    AudioAssetLibrary.bundles.ensureLoaded(BUNDLE).then(() => {
      const bundle: AssetManager.Bundle | null = AudioAssetLibrary.bundles.getBundle(BUNDLE);
      if (!bundle) {
        AudioAssetLibrary.fail('bundle reported resident but is not in memory: ' + BUNDLE);
        return;
      }
      const missing: string[] = [];
      let remaining = CLIP_KEYS.length;
      const done = (): void => {
        remaining -= 1;
        if (remaining > 0) return;
        AudioAssetLibrary.lastError = missing.length ? 'missing audio assets: ' + missing.join(', ') : null;
        AudioAssetLibrary.pending = false;
        const queued = AudioAssetLibrary.waiters;
        AudioAssetLibrary.waiters = [];
        for (const waiter of queued) {
          try {
            waiter();
          } catch (error) {
            console.warn('[AudioAssetLibrary] whenReady callback threw', error);
          }
        }
      };
      for (const key of CLIP_KEYS) {
        bundle.load(AUDIO_CLIP_PATHS[key], AudioClip, (error: Error | null, clip: AudioClip) => {
          if (!error && clip) AudioAssetLibrary.clips.set(key, clip);
          else missing.push(AUDIO_CLIP_PATHS[key]);
          done();
        });
      }
    }).catch((error: unknown) => {
      AudioAssetLibrary.fail('bundle error: ' + (error instanceof Error ? error.message : String(error)));
    });
  }

  private static fail(message: string): void {
    AudioAssetLibrary.lastError = message;
    AudioAssetLibrary.pending = false;
  }

  public static whenReady(callback: () => void): void {
    if (!AudioAssetLibrary.pending) {
      callback();
      return;
    }
    AudioAssetLibrary.waiters.push(callback);
  }

  public static getClip(key: AudioClipKey): AudioClip | null {
    return AudioAssetLibrary.clips.get(key) || null;
  }

  public static isReady(): boolean {
    return AudioAssetLibrary.clips.size === CLIP_KEYS.length;
  }

  public static isPending(): boolean {
    return AudioAssetLibrary.pending;
  }

  public static getLastError(): string | null {
    return AudioAssetLibrary.lastError;
  }

  /** Resident clip keys, for diagnostics and acceptance evidence. */
  public static boundClips(): readonly AudioClipKey[] {
    const bound: AudioClipKey[] = [];
    AudioAssetLibrary.clips.forEach((_clip, key) => { bound.push(key); });
    return bound;
  }

  /** Test hook. */
  public static reset(): void {
    AudioAssetLibrary.clips.clear();
    AudioAssetLibrary.waiters = [];
    AudioAssetLibrary.pending = false;
    AudioAssetLibrary.requested = false;
    AudioAssetLibrary.lastError = null;
  }
}
